### ISSUE TITLE
bthello-app运行报错

### ISSUE THREAD

**Issue by wgetnz** [xieh1995/bthello-app#1]
root@ubuntu-dev:~/bthello-app# python3 main.py -a -port=80
PUT http://192.168.1.211:9200/bt_metadata [status:400 request:0.013s]
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    command_line_runner()
  File "main.py", line 46, in command_line_runner
    me.init_index()
  File "/root/bthello-app/metadata_storage.py", line 14, in init_index
    ElasticsClients.create_index(_index_mappings)
  File "/root/bthello-app/common/database.py", line 82, in create_index
    res = self.es.indices.create(index=self.index_name, body=_index_mappings)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/indices.py", line 107, in create
    params=params, body=body)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'analyzer [ik_max_word] not found for field [file_list]')

**Comment by rehe0x** [comment]
确保ElasticsClients 能正常链接操作

**Comment by 648480505** [comment]
> 确保ElasticsClients 能正常链接操作

一样的问题，能正常连接

**Comment by rehe0x** [comment]
c

> > 确保ElasticsClients 能正常链接操作
> 
> 一样的问题，能正常连接

未安装es ik分词器

**Comment by 648480505** [comment]
> c
> 
> > > 确保ElasticsClients 能正常链接操作
> > 
> > 
> > 一样的问题，能正常连接
> 
> 未安装es ik分词器

谢谢你的答复
